In [65]:
import pandas as pd

In [66]:
import tensorflow as tf

In [67]:
from transformers import AutoTokenizer, TFAutoModel

In [68]:
tokenizer=AutoTokenizer.from_pretrained('distilbert-base-uncased')

'(MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /distilbert-base-uncased/resolve/main/tokenizer_config.json (Caused by NameResolutionError("HTTPSConnection(host=\'huggingface.co\', port=443): Failed to resolve \'huggingface.co\' ([Errno 11001] getaddrinfo failed)"))'), '(Request ID: 21076054-008c-4a2a-b3c5-10a3bb306a71)')' thrown while requesting HEAD https://huggingface.co/distilbert-base-uncased/resolve/main/tokenizer_config.json
Retrying in 1s [Retry 1/5].
'(MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /distilbert-base-uncased/resolve/main/tokenizer_config.json (Caused by NameResolutionError("HTTPSConnection(host=\'huggingface.co\', port=443): Failed to resolve \'huggingface.co\' ([Errno 11001] getaddrinfo failed)"))'), '(Request ID: 52b5f866-08fb-4ba4-b0ae-436e4b960593)')' thrown while requesting HEAD https://huggingface.co/distilbert-base-uncased/resolve/main/tokenizer_

In [69]:
text=["I am Learning transformers by practising it Nice move right??.",
      "This is the second line to test what happens.",
      "This is the third line again, for the same purpose."]

In [70]:
tokens=tokenizer(text,
                 padding=True,
                 truncation=True,
                 return_tensors='tf')
print(tokens)

{'input_ids': <tf.Tensor: shape=(3, 17), dtype=int32, numpy=
array([[  101,  1045,  2572,  4083, 19081,  2011, 10975, 18908,  9355,
         2009,  3835,  2693,  2157,  1029,  1029,  1012,   102],
       [  101,  2023,  2003,  1996,  2117,  2240,  2000,  3231,  2054,
         6433,  1012,   102,     0,     0,     0,     0,     0],
       [  101,  2023,  2003,  1996,  2353,  2240,  2153,  1010,  2005,
         1996,  2168,  3800,  1012,   102,     0,     0,     0]])>, 'attention_mask': <tf.Tensor: shape=(3, 17), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]])>}


In [71]:
print(f"Input ids shape: {tokens['input_ids'].shape}")
print(f"Input atention mask shape: {tokens['attention_mask'].shape}")

Input ids shape: (3, 17)
Input atention mask shape: (3, 17)


In [72]:
print(f"\nInput IDs:\n{tokens['input_ids']}")
print(f"\nInput Attention masks:\n{tokens['attention_mask']}")


Input IDs:
[[  101  1045  2572  4083 19081  2011 10975 18908  9355  2009  3835  2693
   2157  1029  1029  1012   102]
 [  101  2023  2003  1996  2117  2240  2000  3231  2054  6433  1012   102
      0     0     0     0     0]
 [  101  2023  2003  1996  2353  2240  2153  1010  2005  1996  2168  3800
   1012   102     0     0     0]]

Input Attention masks:
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0]]


In [73]:
model=TFAutoModel.from_pretrained("distilbert-base-uncased",use_safetensors=False)

Some layers from the model checkpoint at distilbert-base-uncased were not used when initializing TFDistilBertModel: ['activation_13', 'vocab_projector', 'vocab_transform', 'vocab_layer_norm']
- This IS expected if you are initializing TFDistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFDistilBertModel were initialized from the model checkpoint at distilbert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertModel for predictions without further training.


In [74]:
outputs=model(tokens)

In [75]:
print(outputs)

TFBaseModelOutput(last_hidden_state=<tf.Tensor: shape=(3, 17, 768), dtype=float32, numpy=
array([[[ 2.20871031e-01,  7.54742250e-02,  1.19936213e-01, ...,
         -8.43691751e-02,  3.36341649e-01,  3.63004923e-01],
        [ 6.01343334e-01,  2.87427288e-02, -8.81800801e-02, ...,
         -1.95379809e-01,  4.72915173e-01,  3.71741027e-01],
        [ 3.18101972e-01,  4.56485957e-01,  1.12842649e-01, ...,
         -2.08585277e-01,  3.12930703e-01,  4.15247381e-01],
        ...,
        [ 2.96755433e-01, -2.92393148e-01,  1.04695596e-01, ...,
         -2.80010641e-01,  9.78622809e-02,  2.31774926e-01],
        [ 2.77177803e-02, -6.23123825e-01,  2.75297284e-01, ...,
          8.59816819e-02,  1.47867173e-01, -2.89324880e-01],
        [ 9.73046958e-01,  4.23277408e-01, -3.60569656e-01, ...,
          1.05962306e-01, -4.64780480e-01, -3.32707494e-01]],

       [[-1.48288265e-01, -1.95132419e-01,  9.69076306e-02, ...,
         -1.04272347e-02,  2.87950218e-01,  4.10171092e-01],
        [-4.0

In [76]:
print("\nLast Hidden state shape: \n")
outputs.last_hidden_state.shape


Last Hidden state shape: 



TensorShape([3, 17, 768])

In [77]:
token_embeddings=outputs.last_hidden_state 
attention_mask=tokens['attention_mask']

In [78]:
mask=tf.cast(attention_mask,tf.float32)
mask=tf.expand_dims(mask,axis=-1)

In [79]:
masked_embeddings=token_embeddings*mask
sum_embeddings=tf.reduce_sum(masked_embeddings,axis=1)
sum_mask=tf.reduce_sum(mask,axis=1)
sentence_embeddings=sum_embeddings/sum_mask

In [80]:
print(f"Sentence Embeddings shape: {sentence_embeddings.shape}")
print(sentence_embeddings)

Sentence Embeddings shape: (3, 768)
tf.Tensor(
[[ 0.41552278  0.05296225  0.1476448  ... -0.18735738  0.06943531
   0.13740087]
 [-0.12765019 -0.34959766  0.11867136 ...  0.05103514  0.0351815
   0.10801701]
 [-0.09582864 -0.10354149  0.10216471 ... -0.00803287  0.05200306
   0.21631825]], shape=(3, 768), dtype=float32)


In [81]:
from tensorflow.keras import layers
classifier=layers.Dense(
    units=2,
    activation='softmax'
)

In [82]:
sentiment_logits=classifier(sentence_embeddings)

In [83]:
print(f"Sentiment Output shape: {sentiment_logits.shape}")
print(sentiment_logits)

Sentiment Output shape: (3, 2)
tf.Tensor(
[[0.38451484 0.61548513]
 [0.3941242  0.60587573]
 [0.55034655 0.44965342]], shape=(3, 2), dtype=float32)


In [84]:
num_classes=3
classifier=tf.keras.Sequential([
    tf.keras.layers.Dense(
        num_classes,
        activation='softmax'
    )
])

sentiment_probs=classifier(sentence_embeddings)
print(f"Sentiment Probabilities shape: {sentiment_probs.shape}")
print(sentiment_probs)

Sentiment Probabilities shape: (3, 3)
tf.Tensor(
[[0.33221337 0.41658875 0.2511978 ]
 [0.42829114 0.30165958 0.2700493 ]
 [0.33368778 0.4141574  0.25215483]], shape=(3, 3), dtype=float32)


In [85]:
labels=tf.constant([2,1,0])
loss_fn=tf.keras.losses.SparseCategoricalCrossentropy()
loss_value=loss_fn(labels,sentiment_probs)
print(f"Loss value: {loss_value}")

Loss value: 1.2258400917053223


In [86]:
optimizer=tf.keras.optimizers.Adam(learning_rate=0.01)
with tf.GradientTape() as tape:
    predictions=classifier(sentence_embeddings)
    loss=loss_fn(labels,predictions)

In [87]:
loss.numpy()

1.2258401

In [88]:
gradients=tape.gradient(loss,classifier.trainable_variables)

In [89]:
optimizer.apply_gradients(zip(gradients,classifier.trainable_variables))

<tf.Variable 'UnreadVariable' shape=() dtype=int64, numpy=1>

In [90]:
print(f"Loss after one training step: {loss.numpy()}")

Loss after one training step: 1.2258400917053223


In [91]:
for step in range(20):
    with tf.GradientTape() as tape:
        predictions=classifier(sentence_embeddings)
        loss=loss_fn(labels,predictions)
    gradients=tape.gradient(loss,classifier.trainable_variables)
    optimizer.apply_gradients(zip(gradients,classifier.trainable_variables))
    print(f"Step{step+1} Loss: {loss.numpy():.4f}")

Step1 Loss: 0.6372


Step2 Loss: 0.2988
Step3 Loss: 0.1440
Step4 Loss: 0.0689
Step5 Loss: 0.0354
Step6 Loss: 0.0199
Step7 Loss: 0.0121
Step8 Loss: 0.0077
Step9 Loss: 0.0052
Step10 Loss: 0.0036
Step11 Loss: 0.0025
Step12 Loss: 0.0019
Step13 Loss: 0.0014
Step14 Loss: 0.0011
Step15 Loss: 0.0009
Step16 Loss: 0.0007
Step17 Loss: 0.0006
Step18 Loss: 0.0005
Step19 Loss: 0.0004
Step20 Loss: 0.0004


In [ ]:
final_probs = classifier(sentence_embeddings)

predicted_classes = tf.argmax(final_probs, axis=1)

print("Predicted class indices:", predicted_classes.numpy())

label_map = {
    0: "Negative",
    1: "Neutral",
    2: "Positive"
}

for i, sentence in enumerate(text):
    sentiment = label_map[int(predicted_classes[i])]
    print(f"\nSentence: {sentence}")
    print(f"Predicted Sentiment: {sentiment}")


Predicted class indices: [2 1 0]

Sentence: I am Learning transformers by practising it Nice move right??.
Predicted Sentiment: Positive

Sentence: This is the second line to test what happens.
Predicted Sentiment: Neutral

Sentence: This is the third line again, for the same purpose.
Predicted Sentiment: Negative
